# Generated by Django 6.1.1 on 2026-09-10 12:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ifound', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('local', models.CharField(help_text='Onde foi encontrado ou onde acha que perdeu', max_length=255)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('perdido', 'Perdido (Alguém está procurando)'), ('achado', 'Achado (Alguém encontrou e guardou)'), ('devolvido', 'Devolvido (Entregue ao dono)')], default='achado', max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='itens_imagens/')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_registrados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
